### ISSUE TITLE
deferred_shading sample error on Windows 11

### ISSUE THREAD

**Issue by htlpt** [NVIDIAGameWorks/donut_examples#6]
error with all GAPI backends
![image](https://github.com/user-attachments/assets/b6ec6244-d9e6-4f46-8b51-2350bd43786b)

could be something to do with `CreateGeometryBuffer`?

**Comment by apanteleev** [comment]
Thanks for reporting the issue. It should be fixed with 0a7925d3ffba2dad33f10bcd0a14d855888e19cb, please verify.

**Comment by htlpt** [comment]
All fixed now.
